admin_admin:
    resource: "@AdminAdminBundle/Resources/config/routing.yml"
    prefix:   /

test_test:
    resource: "@TestTestBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
